// Core domain types for Agent Control.
//
// These mirror the domain described in DATA_MODEL.md and GOVERNANCE.md. They
// are used by the UI shell and the mock data layer. Persistence types are
// generated by Prisma; these are the practical UI and domain shapes.

export type RiskLevel = "low" | "medium" | "high";

export type EnvironmentName = "development" | "staging" | "production";

export type AgentStatus = "draft" | "active" | "paused" | "archived";

export type DeploymentStatus =
  | "requested"
  | "pending_approval"
  | "active"
  | "superseded"
  | "rolled_back"
  | "blocked";

export type ApprovalStatus =
  | "pending"
  | "approved"
  | "rejected"
  | "expired"
  | "canceled";

export type EvaluationStatus = "queued" | "running" | "completed" | "failed";

export type PromptVersionStatus =
  | "draft"
  | "in_review"
  | "approved"
  | "archived";

export type IncidentSeverity = "low" | "medium" | "high" | "critical";

export type IncidentStatus = "open" | "acknowledged" | "resolved";

export type UserRole =
  | "administrator"
  | "platform_engineer"
  | "reviewer"
  | "auditor"
  | "executive";

// Audit action names follow the resource.action convention from AUDIT_MODEL.md.
export type AuditAction =
  | "agent.created"
  | "agent.updated"
  | "agent_version.created"
  | "prompt.created"
  | "prompt_version.created"
  | "model.registered"
  | "deployment.requested"
  | "deployment.promoted"
  | "deployment.rolled_back"
  | "deployment.blocked"
  | "approval.requested"
  | "approval.decision_recorded"
  | "evaluation.completed"
  | "incident.created"
  | "incident.resolved";

export interface AgentSummary {
  id: string;
  name: string;
  owner: string;
  environment: EnvironmentName;
  status: AgentStatus;
  riskLevel: RiskLevel;
  errorRate: number;
  evaluationPassRate: number;
  monthlyCost: number;
}

export interface DeploymentActivity {
  id: string;
  agentName: string;
  version: string;
  environment: EnvironmentName;
  status: DeploymentStatus;
  actor: string;
  occurredAt: string;
}

export interface ApprovalSummary {
  id: string;
  resourceType: string;
  resourceLabel: string;
  requestedBy: string;
  assignedTo: string;
  status: ApprovalStatus;
  createdAt: string;
}

export interface IncidentSummary {
  id: string;
  title: string;
  agentName: string;
  severity: IncidentSeverity;
  status: IncidentStatus;
  createdAt: string;
}

export interface AuditActivity {
  id: string;
  action: AuditAction;
  actor: string;
  resourceType: string;
  resourceLabel: string;
  correlationId: string;
  createdAt: string;
}
